In [2]:
import numpy as np

In [4]:
bias=np.array([1,1,1,1,1])
print(bias)
print(bias.shape)

matrix=np.array([[1, 2, 3, 4, 5], 
                 [6,7, 8,9, 10], 
                 [11, 12, 13, 14, 15]])
res=matrix+bias
print(res)

[1 1 1 1 1]
(5,)
[[ 2  3  4  5  6]
 [ 7  8  9 10 11]
 [12 13 14 15 16]]


In [9]:
inputs=np.random.randn(50, 1, 28, 28)
lista=[]
lista+=["kdjf"]
lista+=["kdjf"]
lista+=["kdjf"]
lista+=["abs"]
print(lista[-1])

abs
