In [7]:
from torch.utils.data import DataLoader, TensorDataset
import torch

In [13]:
# Example dataset
x = torch.randn(100, 3)  # 100 samples, each with 3 features
y = torch.randint(0, 2, (100,))  # 100 labels, binary classification

dataset = TensorDataset(x, y)
train_loaderb = DataLoader(dataset, batch_size=10, shuffle=True)
data_batch, lables_batch = next(iter(train_loaderb))
print(data_batch)
print(lables_batch)

tensor([[ 0.9859,  0.9643, -1.0218],
        [ 1.3454, -0.8773, -1.0098],
        [ 0.3094,  0.2441,  0.3179],
        [ 1.6770,  1.0820,  1.7120],
        [-0.4294,  0.2896, -0.1637],
        [ 0.6447, -0.9398,  2.3291],
        [-0.4442, -0.4888, -1.6376],
        [ 1.9886, -1.7159, -0.9858],
        [-0.6345,  1.3975,  0.8271],
        [ 0.0302, -0.5202, -0.1049]])
tensor([0, 1, 1, 0, 1, 1, 1, 0, 1, 1])


In [1]:
import pandas as pd
from dataclasses import dataclass

In [14]:
import zad1
import importlib
importlib.reload(zad1)
from zad1 import *

In [17]:
df = pd.read_csv('data/sst_train_raw.csv')
text_corpus = df.iloc[:, :-1].values
all_words=[]
for text in text_corpus:
    all_words.extend(text[0].split())
all_labels = df.iloc[:, -1].values
all_labels=[la.strip() for la in all_labels]

#intitialize text vocabulary and labels vocabulary, based on TRAIN data
text_vocab=Vocab(corpus=all_words)
labels_vocab=Vocab(corpus=all_labels, usespecialsigns=False)

#intialize the NLPDatasets for train test and valid
train_dataset = NLPDataset(csv_file='data/sst_train_raw.csv', text_vocab=text_vocab, label_vocab=labels_vocab)
#test_dataset = NLPDataset(csv_file=TEST_PATH, text_vocab=text_vocab, label_vocab=labels_vocab)
#valid_dataset = NLPDataset(csv_file=VALID_PATH, text_vocab=text_vocab, label_vocab=labels_vocab)

    #create data loaders
train_loader = DataLoader(train_dataset, batch_size=32, shuffle=False, collate_fn=pad_collate_fn)
#valid_loader = DataLoader(valid_dataset, batch_size=32, shuffle=False, collate_fn=pad_collate_fn)

#test_loader = DataLoader(test_dataset, batch_size=32, shuffle=False, collate_fn=pad_collate_fn)

texts, labels, lengths = next(iter(train_loader))
print(f"Texts shape: {texts.shape}")
print(f"Texts: {texts}")
print(f"Labels: {labels}")
print(f"Lengths: {lengths}")

originalni batch
32
(tensor([    2,  3168,  2133,  5249,     5,     2,  4231,     5,     2,  3412,
         6917,     7,    40,   850,    10,     3,  5196,     5,   673,    62,
           27,  2891,  2114,  5180,  1006,   744,     8,  9485,   575,     5,
        10742,  6887,     8, 11387]), tensor(0))
Texts shape: torch.Size([32, 44])
Texts: tensor([[    2,  3168,  2133,  ...,     0,     0,     0],
        [13240,  5064,  2387,  ...,     0,     0,     0],
        [  193,     2,   675,  ...,     0,     0,     0],
        ...,
        [ 4600,    14,   131,  ...,   327,   322,    44],
        [   48,     8,    17,  ...,     0,     0,     0],
        [   61,     5,     9,  ...,     0,     0,     0]])
Labels: tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0])
Lengths: tensor([34, 33,  7, 26, 21, 17,  7,  4, 12,  6, 12, 22, 22,  6, 13,  5, 11, 15,
         4, 11, 26,  6, 14, 36, 12, 12, 27, 15,  6, 44,  9, 13])


In [3]:
data_frame = pd.read_csv('data/sst_train_raw.csv')

In [4]:
text_corpus = data_frame.iloc[:, :-1].values
allwords=[]
for text in text_corpus:
    allwords.extend(text[0].split())
alllabels = data_frame.iloc[:, -1].values
alllabels=[la.strip() for la in alllabels]